create-entry first draft
Justin-Arakaki/code-journal pull request #5
Opened 2022-02-15 02:02 UTC by Justin-Arakaki

![code-journal 1](https://user-images.githubusercontent.com/97260501/153978594-611f5c9f-4dbe-4df9-b609-b91cd3b2a4f4.gif)

2022-02-15 02:08 UTC, Zhiwutian requested changes
A couple small updates!

2022-02-15 02:08 UTC, Zhiwutian commented on js/main.js
> +  data.entries.push(newEntry);
this should be unshift, because you want the newest entry at the front of the array

2022-02-15 02:08 UTC, Zhiwutian commented on js/main.js
> +  localStorage.setItem('data-local-storage', dataJSON);
local storage functionality should only be done when the page unloads, you don't want to directly access it here.

2022-02-15 18:13 UTC, Zhiwutian approved these changes
👍🏼

2022-02-16 01:14 UTC, Justin-Arakaki commented
![code-journal 2](https://user-images.githubusercontent.com/97260501/154177406-ebe7988a-31ab-4c55-8412-8069121f571b.gif)

2022-02-16 01:15 UTC, Zhiwutian approved these changes
👍🏼

2022-02-16 18:07 UTC, merged